Added memory use improvements.
ImpulsoGov/farolcovid pull request #227
Opened 2020-12-16 12:54 UTC by lsDantas

2020-12-16 19:08 UTC, fernandascovino requested changes

2020-12-16 19:08 UTC, fernandascovino commented on src/pages/onda_covid.py
> +        load_states_heatmap(br_cases)
@lsDantas mudar aqui para deixar chamadas de `load_[...]_heatmap` dentro de `if`, de acordo com a localidade que a pessoa selecionar. a ideia é que só apareça 1 heatmapo por vez, deixar por padrão o de estado ;)

2020-12-17 16:59 UTC, lsDantas commented on src/pages/onda_covid.py
> +        load_states_heatmap(br_cases)
Mudança implementada.

2020-12-17 20:46 UTC, fernandascovino approved these changes

2020-12-17 20:46 UTC, merged